#!/bin/bash

OS_NAME=$(uname)

if [ $OS_NAME == "Darwin" ]; then

    echo '-> Running spark-submit after compile && assembly'
    sbt compile
    sbt package
    spark-submit --name "cienaML" --class Main --master "local[4]"  target/scala-2.10/CienaML-assembly-1.0.jar
fi
