#!/bin/bash

OS_NAME=$(uname)

if [ $OS_NAME == "Darwin" ]; then

    echo '-> Running spark-submit after compile && package'
    sbt compile
    sbt package
    spark-submit --name "SparkStats" --class Main --master "local[4]"  target/scala-2.10/sparkstats_2.10-1.0.jar
fi
